[package]
name = "nbplay_js"
version = "0.1.0"
edition = "2021"
publish = false
keywords = ["experimental"]
include = ["src/**/*", "Cargo.toml", "package.json"]

[lib]
name = "nbplay"
path = "src/rust/lib.rs"
crate-type = ["cdylib"]

[dependencies]
nbplay = { path = "../rust", version = "*" }
wasm-bindgen = "0.2.114"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3"
features = [
    "AudioContext",
    "AudioContextOptions",
    "AudioBuffer",
    "AudioBufferSourceNode",
    "AudioDestinationNode",
    "AudioNode",
    "AudioParam",
    "GainNode",
    "GainOptions",
    "OscillatorNode",
    "OscillatorType",
    "MidiAccess",
    "MidiInput",
    "MidiInputMap",
    "MidiMessageEvent",
    "MidiPort",
    "Navigator",
    "Window",
    "console",
]
